import { TrashType } from "../types/game";

export interface WasteItem {
  id: number;
  name: string;
  correctContainer: TrashType;
  description?: string;
}

export const WASTE_ITEMS: WasteItem[] = [
  // PLÁSTICO (38 items)
  { id: 1, name: "Botella de agua", correctContainer: "plastic" },
  { id: 2, name: "Envase de yogur", correctContainer: "plastic" },
  { id: 3, name: "Bolsa de supermercado", correctContainer: "plastic" },
  { id: 4, name: "Botella de refresco", correctContainer: "plastic" },
  { id: 5, name: "Envase de champú", correctContainer: "plastic" },
  { id: 6, name: "Tapón de botella", correctContainer: "plastic" },
  { id: 7, name: "Envase de detergente", correctContainer: "plastic" },
  { id: 8, name: "Bolsa de pan", correctContainer: "plastic" },
  { id: 9, name: "Botella de aceite vacía", correctContainer: "plastic" },
  { id: 10, name: "Vaso de plástico", correctContainer: "plastic" },
  { id: 11, name: "Plato desechable", correctContainer: "plastic" },
  { id: 12, name: "Cubiertos de plástico", correctContainer: "plastic" },
  { id: 13, name: "Envase de margarina", correctContainer: "plastic" },
  { id: 14, name: "Botella de suavizante", correctContainer: "plastic" },
  { id: 15, name: "Envase de crema", correctContainer: "plastic" },
  { id: 16, name: "Bolsa de congelados", correctContainer: "plastic" },
  { id: 17, name: "Envase de helado", correctContainer: "plastic" },
  { id: 18, name: "Botella de lejía vacía", correctContainer: "plastic" },
  { id: 19, name: "Envase de pasta de dientes", correctContainer: "plastic" },
  { id: 20, name: "Bolsa de basura", correctContainer: "plastic" },
  { id: 21, name: "Envase de queso fresco", correctContainer: "plastic" },
  { id: 22, name: "Botella de gel", correctContainer: "plastic" },
  { id: 23, name: "Envase de mantequilla", correctContainer: "plastic" },
  { id: 24, name: "Bolsa de cereales", correctContainer: "plastic" },
  { id: 25, name: "Envase de miel", correctContainer: "plastic" },
  { id: 26, name: "Botella de vinagre", correctContainer: "plastic" },
  { id: 27, name: "Envase de salsa", correctContainer: "plastic" },
  { id: 28, name: "Bolsa de verduras", correctContainer: "plastic" },
  { id: 29, name: "Envase de mermelada plástico", correctContainer: "plastic" },
  { id: 30, name: "Botella de ketchup", correctContainer: "plastic" },
  { id: 31, name: "Envase de mayonesa", correctContainer: "plastic" },
  { id: 32, name: "Film transparente", correctContainer: "plastic" },
  { id: 33, name: "Bote de vitaminas", correctContainer: "plastic" },
  { id: 34, name: "Envase de complementos", correctContainer: "plastic" },
  { id: 35, name: "Botella de agua oxigenada", correctContainer: "plastic" },
  { id: 36, name: "Envase de protector solar", correctContainer: "plastic" },
  { id: 37, name: "Bolsa zip", correctContainer: "plastic" },
  { id: 38, name: "Envase de comida para mascotas", correctContainer: "plastic" },

  // VIDRIO (38 items)
  { id: 39, name: "Botella de vino", correctContainer: "glass" },
  { id: 40, name: "Tarro de mermelada", correctContainer: "glass" },
  { id: 41, name: "Botella de cerveza", correctContainer: "glass" },
  { id: 42, name: "Frasco de perfume", correctContainer: "glass" },
  { id: 43, name: "Botella de whisky", correctContainer: "glass" },
  { id: 44, name: "Tarro de miel", correctContainer: "glass" },
  { id: 45, name: "Botella de cava", correctContainer: "glass" },
  { id: 46, name: "Frasco de colonia", correctContainer: "glass" },
  { id: 47, name: "Botella de aceite de oliva", correctContainer: "glass" },
  { id: 48, name: "Tarro de conservas", correctContainer: "glass" },
  { id: 49, name: "Botella de zumo", correctContainer: "glass" },
  { id: 50, name: "Vaso de cristal", correctContainer: "glass" },
  { id: 51, name: "Botella de licor", correctContainer: "glass" },
  { id: 52, name: "Tarro de pickles", correctContainer: "glass" },
  { id: 53, name: "Botella de ginebra", correctContainer: "glass" },
  { id: 54, name: "Frasco de medicinas", correctContainer: "glass" },
  { id: 55, name: "Botella de vinagre", correctContainer: "glass" },
  { id: 56, name: "Tarro de mostaza", correctContainer: "glass" },
  { id: 57, name: "Botella de ron", correctContainer: "glass" },
  { id: 58, name: "Frasco de especias", correctContainer: "glass" },
  { id: 59, name: "Botella de sidra", correctContainer: "glass" },
  { id: 60, name: "Tarro de pepinillos", correctContainer: "glass" },
  { id: 61, name: "Botella de agua mineral", correctContainer: "glass" },
  { id: 62, name: "Frasco de mermelada artesanal", correctContainer: "glass" },
  { id: 63, name: "Botella de vermut", correctContainer: "glass" },
  { id: 64, name: "Tarro de aceitunas", correctContainer: "glass" },
  { id: 65, name: "Botella de champán", correctContainer: "glass" },
  { id: 66, name: "Frasco de café instantáneo", correctContainer: "glass" },
  { id: 67, name: "Botella de salsa de tomate", correctContainer: "glass" },
  { id: 68, name: "Tarro de pimientos", correctContainer: "glass" },
  { id: 69, name: "Botella de aperitivo", correctContainer: "glass" },
  { id: 70, name: "Frasco de vainilla", correctContainer: "glass" },
  { id: 71, name: "Botella de tónica", correctContainer: "glass" },
  { id: 72, name: "Tarro de salsa", correctContainer: "glass" },
  { id: 73, name: "Botella de limoncello", correctContainer: "glass" },
  { id: 74, name: "Frasco de extractos", correctContainer: "glass" },
  { id: 75, name: "Botella de brandy", correctContainer: "glass" },
  { id: 76, name: "Tarro de tomates secos", correctContainer: "glass" },

  // PAPEL (38 items)
  { id: 77, name: "Periódico", correctContainer: "paper" },
  { id: 78, name: "Revista", correctContainer: "paper" },
  { id: 79, name: "Caja de cartón", correctContainer: "paper" },
  { id: 80, name: "Folleto publicitario", correctContainer: "paper" },
  { id: 81, name: "Sobre de carta", correctContainer: "paper" },
  { id: 82, name: "Cuaderno usado", correctContainer: "paper" },
  { id: 83, name: "Caja de cereales", correctContainer: "paper" },
  { id: 84, name: "Papel de regalo", correctContainer: "paper" },
  { id: 85, name: "Catálogo comercial", correctContainer: "paper" },
  { id: 86, name: "Ticket de compra", correctContainer: "paper" },
  { id: 87, name: "Caja de zapatos", correctContainer: "paper" },
  { id: 88, name: "Papel de oficina", correctContainer: "paper" },
  { id: 89, name: "Envoltorio de regalo", correctContainer: "paper" },
  { id: 90, name: "Factura", correctContainer: "paper" },
  { id: 91, name: "Caja de pizza", correctContainer: "paper" },
  { id: 92, name: "Libreta vieja", correctContainer: "paper" },
  { id: 93, name: "Caja de medicinas", correctContainer: "paper" },
  { id: 94, name: "Papel de carta", correctContainer: "paper" },
  { id: 95, name: "Envase tetrabrik", correctContainer: "paper" },
  { id: 96, name: "Agenda antigua", correctContainer: "paper" },
  { id: 97, name: "Caja de galletas", correctContainer: "paper" },
  { id: 98, name: "Papel bond", correctContainer: "paper" },
  { id: 99, name: "Carpeta de documentos", correctContainer: "paper" },
  { id: 100, name: "Recibo", correctContainer: "paper" },
  { id: 101, name: "Caja de envío", correctContainer: "paper" },
  { id: 102, name: "Papel de periódico", correctContainer: "paper" },
  { id: 103, name: "Bolsa de papel", correctContainer: "paper" },
  { id: 104, name: "Postal", correctContainer: "paper" },
  { id: 105, name: "Caja de té", correctContainer: "paper" },
  { id: 106, name: "Papel de fax", correctContainer: "paper" },
  { id: 107, name: "Guía telefónica", correctContainer: "paper" },
  { id: 108, name: "Documento impreso", correctContainer: "paper" },
  { id: 109, name: "Caja de pasta", correctContainer: "paper" },
  { id: 110, name: "Papel de impresora", correctContainer: "paper" },
  { id: 111, name: "Caja de pañuelos", correctContainer: "paper" },
  { id: 112, name: "Formulario", correctContainer: "paper" },
  { id: 113, name: "Caja de arroz", correctContainer: "paper" },
  { id: 114, name: "Volante", correctContainer: "paper" },

  // ORGÁNICO (36 items)
  { id: 115, name: "Cáscara de plátano", correctContainer: "organic" },
  { id: 116, name: "Restos de manzana", correctContainer: "organic" },
  { id: 117, name: "Cáscara de naranja", correctContainer: "organic" },
  { id: 118, name: "Huesos de pollo", correctContainer: "organic" },
  { id: 119, name: "Piel de patata", correctContainer: "organic" },
  { id: 120, name: "Restos de lechuga", correctContainer: "organic" },
  { id: 121, name: "Cáscara de huevo", correctContainer: "organic" },
  { id: 122, name: "Restos de pescado", correctContainer: "organic" },
  { id: 123, name: "Hojas de verduras", correctContainer: "organic" },
  { id: 124, name: "Restos de pan", correctContainer: "organic" },
  { id: 125, name: "Cáscara de limón", correctContainer: "organic" },
  { id: 126, name: "Huesos de cerdo", correctContainer: "organic" },
  { id: 127, name: "Restos de tomate", correctContainer: "organic" },
  { id: 128, name: "Posos de café", correctContainer: "organic" },
  { id: 129, name: "Cáscara de cebolla", correctContainer: "organic" },
  { id: 130, name: "Restos de arroz", correctContainer: "organic" },
  { id: 131, name: "Hojas de té", correctContainer: "organic" },
  { id: 132, name: "Restos de pasta", correctContainer: "organic" },
  { id: 133, name: "Cáscara de ajo", correctContainer: "organic" },
  { id: 134, name: "Huesos de ternera", correctContainer: "organic" },
  { id: 135, name: "Restos de verduras", correctContainer: "organic" },
  { id: 136, name: "Flores marchitas", correctContainer: "organic" },
  { id: 137, name: "Restos de fruta", correctContainer: "organic" },
  { id: 138, name: "Cáscara de sandía", correctContainer: "organic" },
  { id: 139, name: "Huesos de cordero", correctContainer: "organic" },
  { id: 140, name: "Restos de ensalada", correctContainer: "organic" },
  { id: 141, name: "Cáscara de melón", correctContainer: "organic" },
  { id: 142, name: "Restos de carne", correctContainer: "organic" },
  { id: 143, name: "Hojas secas", correctContainer: "organic" },
  { id: 144, name: "Restos de sopa", correctContainer: "organic" },
  { id: 145, name: "Cáscara de piña", correctContainer: "organic" },
  { id: 146, name: "Espinas de pescado", correctContainer: "organic" },
  { id: 147, name: "Restos de verdura cocida", correctContainer: "organic" },
  { id: 148, name: "Pulpa de fruta", correctContainer: "organic" },
  { id: 149, name: "Restos de comida", correctContainer: "organic" },
  { id: 150, name: "Hierba cortada", correctContainer: "organic" }
];

export function getRandomWasteItem(): WasteItem {
  const randomIndex = Math.floor(Math.random() * WASTE_ITEMS.length);
  return WASTE_ITEMS[randomIndex];
}

export function getWasteItemsByType(type: TrashType): WasteItem[] {
  return WASTE_ITEMS.filter(item => item.correctContainer === type);
}